---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
  - ["forwarded_port", {guest: 8443, host: 8443}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.8
  - name: centos-6.6
  - name: centos-7.0

suites:
- name: package
  run_list:
    - recipe[nexus]
  attributes:
    nexus:
      cli:
        ssl:
          verify: false
      app_server_proxy:
        use_self_signed: true
- name: source
  run_list:
    - recipe[nexus]
  attributes:
    nexus:
      cli:
        ssl:
          verify: false
      app_server_proxy:
        use_self_signed: true
- name: lwrp
  run_list:
    - recipe[nexus]
    - recipe[nexus-test::lwrp]
  attributes:
    nexus:
      cli:
        ssl:
          verify: false
      app_server_proxy:
        use_self_signed: true
